mac_address: 00:11:22:33:44:55
mii_config:
  type: rmii
  speed: 100
  mode: mac
virtual_interfaces:
  - name: ecu1_controller1_iface1_viface1
    vlanid: 10
    addresses:
      - address: 10.0.10.1
        ipv4netmask: 255.255.255.0
compute_nodes:
  - name: ecu1_c1_vm1
    mac_address: 00:11:22:33:44:56
    virtual_interfaces:
      - name: ecu1_c1_vm1_viface1
        vlanid: 20
        addresses:
          - address: 10.0.20.1
            ipv4netmask: 255.255.255.0
  - name: ecu1_c1_vm2
    mac_address: 00:11:22:33:44:57
    virtual_interfaces:
      - name: ecu1_c1_vm2_viface1
        vlanid: 20
        addresses:
          - address: 10.0.20.2
            ipv4netmask: 255.255.255.0
