mac_address: 00:11:02:02:01:01
mii_config:
  type: rmii
  speed: 100
  mode: phy
virtual_interfaces:
  - name: hpc_c2_i1_viface1
    vlanid: 40
    addresses:
      - address: 10.0.40.6
        ipv4netmask: 255.255.255.0
  - name: hpc_c1_i1_viface2
    vlanid: 30
    addresses:
      - address: 10.0.30.6
        ipv4netmask: 255.255.255.0
macsec_config:
  vlan_bypass: []
  mka_enabled: true
  hello_time: 1000
  bounded_hello_time: 2000
  life_time: 100000
  sak_retire_time: 20000
  macsec_mode: integrity
  kay_on: true
  key_role: key_server_always
  delay_protect: false
  participant_activation: always