mac_address: 00:11:22:33:44:55
mii_config:
  type: rmii
  speed: 100
  mode: phy
virtual_interfaces:
  - name: ecu1_controller1_iface1_viface1
    vlanid: 10
    addresses:
      - address: 10.0.10.1
        ipv4netmask: 255.255.255.0
  - name: ecu1_controller1_iface1_viface2
    vlanid: 20
    addresses:
      - address: 10.0.20.1
        ipv4netmask: 255.255.255.0
  - name: ecu1_controller1_iface1_viface3
    vlanid: 30
    addresses:
      - address: 10.0.30.1
        ipv4netmask: 255.255.255.0
