mac_address: 00:11:03:01:01:01
mii_config:
  type: rmii
  speed: 100
  mode: phy
virtual_interfaces:
  - name: z1_c1_i1_viface1
    vlanid: 10
    addresses:
      - address: 10.0.10.1
        ipv4netmask: 255.255.255.0
  - name: z1_c1_i1_viface2
    vlanid: 50
    addresses:
      - address: 10.0.50.1
        ipv4netmask: 255.255.255.0
  - name: z1_c1_i1_viface3
    vlanid: 40
    addresses:
      - address: 10.0.40.1
        ipv4netmask: 255.255.255.0
    multicast:
    - 224.0.0.1
ptp_config:
  cmlds_linkport_enabled: false
  ptp_ports:
    - domain_id: 0
      src_port_identity: 6
      sync_config:
        type: time_transmitter
        log_tx_period: -3
        two_step: true
        tlv: []
macsec_config:
  vlan_bypass: []
  mka_enabled: true
  hello_time: 1000
  bounded_hello_time: 2000
  life_time: 100000
  sak_retire_time: 20000
  macsec_mode: integrity
  kay_on: true
  key_role: key_server_always
  delay_protect: false
  participant_activation: always