mac_address: 00:11:02:01:01:01
mii_config:
  type: rmii
  speed: 100
  mode: phy
virtual_interfaces:
  - name: hpc_c1_i1_viface1
    vlanid: 10
    addresses:
      - address: 10.0.10.5
        ipv4netmask: 255.255.255.0
    multicast:
    - 91:E0:F0:00:00:AA
    - 91:E0:F0:00:00:BB
  - name: hpc_c1_i1_viface2
    vlanid: 20
    addresses:
      - address: 10.0.20.5
        ipv4netmask: 255.255.255.0
    multicast:
      - 224.244.224.245
      - 224.0.0.15
  - name: hpc_c1_i1_viface3
    vlanid: 50
    addresses:
      - address: 10.0.50.5
        ipv4netmask: 255.255.255.0
  - name: hpc_c1_i1_viface4
    vlanid: 40
    addresses:
      - address: 10.0.40.5
        ipv4netmask: 255.255.255.0
    multicast:
    - 224.0.0.1
ptp_config:
  cmlds_linkport_enabled: false
  ptp_ports:
    - domain_id: 0
      src_port_identity: 1
      sync_config:
        type: time_receiver
        sync_timeout: 3
        sync_followup_timeout: 10
      pdelay_config:
        log_tx_period: 1
macsec_config:
  vlan_bypass: []
  mka_enabled: true
  hello_time: 1000
  bounded_hello_time: 2000
  life_time: 100000
  sak_retire_time: 20000
  macsec_mode: integrity
  kay_on: true
  key_role: key_server_always
  delay_protect: false
  participant_activation: always